#!/bin/bash
echo "=========================================="
echo "    Memory Analysis Lab - Quick Reference"
echo "=========================================="
echo ""
echo "Available Commands:"
echo "  vol -f infected_system.raw windows.info       # System information"
echo "  vol -f infected_system.raw windows.pslist     # Process list"
echo "  vol -f infected_system.raw windows.pstree     # Process tree"
echo "  vol -f infected_system.raw windows.netstat    # Network connections"
echo "  vol -f infected_system.raw windows.malfind    # Malware detection"
echo "  vol -f infected_system.raw windows.cmdline    # Command history"
echo ""
echo "Useful Aliases:"
echo "  evidence  # Change to /evidence directory"
echo "  lab       # Change to /home/ubuntu/lab directory"
echo "  help      # Show analysis checklist"
echo ""
echo "Current directory: $(pwd)"
echo "Files in current directory:"
ls -la
echo ""
echo "Memory dump location: /evidence/infected_system.raw"
echo "Memory dump size: $(du -h /evidence/infected_system.raw 2>/dev/null || echo 'Not found')"
echo "=========================================="
